version: '3.7'

services:
  web:
    build:
      args:
        PLATFORM: ${PLATFORM:-linux/amd64}
      context: .
    image: taskogotchi-web:local
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./static:/app/web/static
      - ./media:/app/web/media
      - .:/app/web/
    expose:
      - 8000
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - .env-db

  redis:
    image: redis:7-alpine

  nginx:
    build:
      context: ./nginx
    volumes:
      - ./static:/app/web/static
      - ./media:/app/web/media
      - /etc/nginx/conf.d/nginx.conf:./nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
      - db

volumes:
  postgres_data:
